FROM python:3.9

WORKDIR /app

COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install pytest
RUN pip install pytest

EXPOSE 8000

ENV NAME World
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
